name: drone_sale
description: "E-commerce for drone sale"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  url_strategy: ^0.2.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Firebase dependencies
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_analytics: ^10.8.10
  firebase_messaging: ^14.7.20
  firebase_storage: ^11.6.10
  firebase_remote_config: ^4.3.18
  firebase_performance: ^0.9.3+15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  assets:
    - assets/images/background.png
    - assets/images/logo.png
    - assets/images/coming soon.jpeg
    - assets/images/gmail logo.png
    - assets/images/whatsapp logo.jpeg
    - assets/images/contact logo.png
    - assets/images/redback.jpeg
    - assets/images/redback2.jpeg
    - assets/images/redback3.jpeg
    - assets/images/linkedin image.png
    - assets/images/instagram image.jpeg
    - assets/images/backgroundtwo.jpg

  uses-material-design: true