name: Firebase Deploy

on:
  push:
    branches:
      - main  # or the branch you want to trigger deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Set up Firebase authentication
      run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > ./firebase-key.json

    - name: Authenticate Firebase
      run: firebase auth:import --project <your-project-id> --key-file ./firebase-key.json

    - name: Deploy to Firebase
      run: firebase deploy --only hosting
