name: Firebase Deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Upgrade to the latest LTS version of Node.js

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: npm install

      - name: Build Flutter Web
        run: flutter build web

      - name: Authenticate Firebase
        run: firebase use --add 1//0gS8KQWMjBhYvCgYIARAAGBASNwF-L9IrybGyES9wgkseOmyV7tEyj95XdtMM4a6wdLb4l-5LU4OfLEwl8CJNbvS-Fy06i2IasBY --token "${{ secrets.FIREBASE_TOKEN }}"  # Use token-based auth for Firebase CLI

      - name: Deploy to Firebase
        run: firebase deploy --only hosting
