name: Firebase Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Job started"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Use the latest LTS version of Node.js for stability

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.3  # The Flutter version you're using

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Add Firebase CLI to PATH
        run: echo "::add-path::$(npm bin -g)"

      - name: Install Flutter dependencies
        run: flutter pub get  # Ensure you install Flutter dependencies

      - name: Build Flutter Web
        run: flutter build web

      - name: Authenticate Firebase
        run: firebase use --token "${{ secrets.FIREBASE_TOKEN }}"  # Authenticate using Firebase token

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"  # Deploy hosting

      - name: Complete job
        run: echo "Deployment complete"
