name: Firebase Deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17.0'  # Upgrade to the latest LTS version of Node.js

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.3

      - name: Install dependencies
        run: npm ci

      - name: Build Flutter Web
        run: flutter build web

      - name: Authenticate Firebase
        run: firebase use --add 1//0gW1Q6bBdfZHJCgYIARAAGBASNwF-L9IrmUA5UiY32yWfDxFx0O9EhzdmaWS8pvvs1h7rLX9KDVOeAsQZUnQj4LxnatV7Ss1KEXc --token "${{ secrets.FIREBASE_TOKEN }}"  # Use token-based auth for Firebase CLI

      - name: Deploy to Firebase
        run: firebase deploy --only hosting


