name: Firebase Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Job started"

      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Use the latest LTS version of Node.js

      # Install Flutter SDK
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'  # Specify the Flutter version you're using

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Set up Google Application Credentials from GitHub Secret
      - name: Set up Google Application Credentials
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      # Export Google Application Credentials as environment variable
      - name: Set Firebase Application Credentials
        run: export GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/firebase-key.json

      # Install Flutter dependencies
      - name: Install Flutter dependencies
        run: flutter pub get

      # Build Flutter Web
      - name: Build Flutter Web
        run: flutter build web

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      # Completion message
      - name: Complete job
        run: echo "Deployment complete"
