name: Firebase Deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Upgrade to the latest LTS version of Node.js

      - name: Install dependencies
        run: npm install

      - name: Authenticate Firebase
        run: firebase use --add <your-project-id> --token "${{ secrets.FIREBASE_TOKEN }}"  # Use token-based auth for Firebase CLI

      - name: Deploy to Firebase
        run: firebase deploy --only hosting
