name: Firebase Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Job started"

      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Use the latest LTS version of Node.js

      # Install Flutter SDK
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.3  # The Flutter version you're using

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Authenticate with Firebase
      - name: Authenticate with Firebase
        run: firebase login:ci --token "${{ secrets.FIREBASE_TOKEN }}"

      # Install Flutter dependencies
      - name: Install Flutter dependencies
        run: flutter pub get

      # Build Flutter Web
      - name: Build Flutter Web
        run: flutter build web

      # Set Google Application Credentials
      - name: Set Google Application Credentials
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > C:\Users\Ajithpall\Desktop\PROJECTS\DRONEDOC\.firebase\dronedoc-122002-firebase-adminsdk-4d5qn-f5abbaa548.json

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting

      # Completion message
      - name: Complete job
        run: echo "Deployment complete"
